const DashboardTypes = {
    USER_DATA_REQUEST: "USER_DATA_REQUEST",
    USER_DATA_REQUEST_SUCCESS: "USER_DATA_REQUEST_SUCCESS",
    PERSON_REQUST: 'PERSON_REQUST',
    PERSON_REQUST_SUCCESS: "PERSON_REQUST_SUCCESS",
    POST_REQUEST: 'POST_REQUEST',
    POST_SUCCESS: 'POST_SUCCESS',
    DELETE_REQUEST: 'DELETE_REQUEST',
    DELETE_SUCCESS: 'DELETE_SUCCESS',


};

export { DashboardTypes };

